### PR TITLE
Display Credits on GitHub

### PR DESCRIPTION
**Pull request by Kooddammn**
https://github.com/ShortDevelopment/Nearby-Sharing-Windows/compare/master...Kooddammn:Nearby-Sharing-Windows:master?expand=1#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5

### CODE REVIEW

**Comment by ShortDevelopment** [comment]
Hey @Kooddammn, were you referring to #79?
I actually meant to display the Credits inside the App but it would of cause be nice to see them on GitHub too!

Could you maybe just link the credits to the Readme, so that we can still maintain them in a separate file?

**Comment by ShortDevelopment** [comment]
Please also don't forget to put yourself in the credit file!
You could just add a new heading
```diff
# Credits
## Contributions
...
 
## Translations
...

+ ## Documentation
```

**Comment by Kooddammn** [comment]
Hi @ShortDevelopment ,
Since the requirement what saying to display the content , so assume it to display it on the github but anyway now it is fine to display ,only point i didn't got what you told to link credits to the readme , can you elaborate that?

> Hey @Kooddammn, were you referring to #79? I actually meant to display the Credits inside the App but it would of cause be nice to see them on GitHub too!
> 
> Could you maybe just link the credits to the Readme, so that we can still maintain them in a separate file?

**Comment by ShortDevelopment** [comment]
You could simply create a link with Markdown
```markdown
[Credits](https://nearshare.shortdev.de/CREDITS)
```

I would use the explicit link to the page hosted via github-pages to get correct formatting.
Otherwise it would look like this: https://nearshare.shortdev.de/CREDITS.md

**Pull request closed without merging**
